version: "3.9"

services:
  mongo:
    image: mongo
    networks: 
      - my-network
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    networks: 
      - my-network  
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/testdb?authSource=admin
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks: 
      - my-network
    environment:
      REACT_APP_API_URL: http://backend:3001
    depends_on:
      - backend

networks:
  my-network:
    external: true