pipeline {
    agent any


    environment {
        NEXUS_URL = "http://127.0.0.1:8081"
        REPO_NAME = "travelmemory"
        ARTIFACT_NAME = "travelmemory-${BUILD_NUMBER}.zip"
    }

    stages {

        stage('Checkout') {
            steps {
               git credentialsId: 'git-credentials',
                  url: 'git@github.com:srikar2011/travelmemory.git',
                  branch: 'main'
            }
        }

        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('SonarQube') {
          		powershell '''
            			$env:PATH = "C:\\tools\\sonar-scanner\\bin;$env:PATH"

            			Write-Host "Running SonarQube analysis..."
            			Write-Host "Project: $env:SONAR_PROJECT"
            			Write-Host "Build: $env:BUILD_NUMBER"

            			sonar-scanner.bat `
              				"-Dsonar.projectKey=$env:SONAR_PROJECT" `
              				"-Dsonar.projectName=Terraform Infrastructure" `
              				"-Dsonar.sources=." `
              				"-Dsonar.exclusions=**/.terraform/**,*.tfstate*,**/*.tfvars" `
              				"-Dsonar.projectVersion=$env:BUILD_NUMBER"

            if ($LASTEXITCODE -ne 0) {
              		Write-Host "ERROR: SonarQube analysis failed"
              		exit 1
           			 }
                  	Write-Host "SonarQube analysis complete"
          		'''
       			 }
            }
        }

        stage('Package') {
            steps {
                bat """
                powershell Compress-Archive -Path * -DestinationPath ${ARTIFACT_NAME}
                """
            }
        }

        stage('Upload to Nexus') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'nexus-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    bat """
                    curl -u %USER%:%PASS% --upload-file ${ARTIFACT_NAME} ^
                    ${NEXUS_URL}/repository/${REPO_NAME}/${ARTIFACT_NAME}
                    """
                }
            }
        }
    }
}